language: node_js
node_js:
    -  "5.1.1"
env:
    - CXX=g++-5
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
script:
    - npm run lint
    - npm test
